# Generated by Django 5.1.2 on 2024-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskAssignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='taskAssignment.user'),
        ),
    ]
